<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <RootNamespace>FlashBoxApp</RootNamespace>
    <AssemblyName>FlashBox</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
    <OutputPath>bin\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Prefer32Bit>true</Prefer32Bit>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>flash\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="ICSharpCode.SharpZipLib">
      <HintPath>flash\ICSharpCode.SharpZipLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="AxInterop.ShockwaveFlashObjects">
      <HintPath>flash\AxInterop.ShockwaveFlashObjects.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Interop.ShockwaveFlashObjects">
      <HintPath>flash\Interop.ShockwaveFlashObjects.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.Core">
      <HintPath>packages\Microsoft.Web.WebView2\lib\net462\Microsoft.Web.WebView2.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.WinForms">
      <HintPath>packages\Microsoft.Web.WebView2\lib\net462\Microsoft.Web.WebView2.WinForms.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="FlashCore.cs" />
    <Compile Include="Downloads.cs" />
    <Compile Include="AppForm.cs" />
    <Compile Include="Headless.cs" />
    <Content Include="ui\index.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\drop.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\drop.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\weapon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\armor.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\helm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\cape.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\pet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\misc.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\cosmetic.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ui\icons\search.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\char6.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\char6-orig.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Chaos.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\ClubHouse.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Frostvale.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Hill.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Mystcroft.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Shadowscythe.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Yulgar.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\cp-*.swf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Newtonsoft.Json.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\ICSharpCode.SharpZipLib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\AxInterop.ShockwaveFlashObjects.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="flash\Interop.ShockwaveFlashObjects.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="packages\Microsoft.Web.WebView2\build\Microsoft.Web.WebView2.targets" Condition="Exists('packages\Microsoft.Web.WebView2\build\Microsoft.Web.WebView2.targets')" />
</Project>
